#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: user-management-service
#          uri: lb://USER-MANAGEMENT-SERVICE
#          predicates:
#            - Path=/api/users/**
#        - id: parking-management-service
#          uri: lb://PARKING-MANAGEMENT-SERVICE
#          predicates:
#            - Path=/api/parking/**
#  config:
#    import: optional:configserver:http://localhost:8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 7075
spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/carparking
    username: root
    password: Hari@950

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9091
