spring:
  application:
    name: parking-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/carparking
    username: root
    password: Hari@950
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9092