server:
  port: 7075
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users/**
        - id: parking-management-service
          uri: lb://PARKING-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/parking/**
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka