#server:
#  port: 9091
#spring:
#  application:
#    name: user-management-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/carparking
#    username: root
#    password: Hari@950
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 9091

spring:
  application:
    name: user-management-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/carparking
    username: root
    password: Hari@950

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
